"""Add broker and market columns to strategies table

Revision ID: 2497826f900a
Revises: 929847481e51
Create Date: 2025-11-16 02:28:07.790638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2497826f900a'
down_revision: Union[str, Sequence[str], None] = '929847481e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('broker', sa.String(), nullable=False))
    op.add_column('strategies', sa.Column('market', sa.String(), nullable=False))
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=False)
    op.drop_column('strategies', 'market')
    op.drop_column('strategies', 'broker')
    # ### end Alembic commands ###
